### ISSUE TITLE
`AttributeError: 'MHApplication' object has no attribute 'mhapi'` prevents plugin load.

### ISSUE THREAD

**Issue by gabrielmontagne** [makehumancommunity/community-plugins-socket#5]
When running against the `makehuman` `master` branch, I get the following error on the logs, 

```
Traceback (most recent call last):
  File "./core/mhmain.py", line 580, in loadPlugin
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabriel/los-fuegos/makehuman/makehuman/plugins/8_server_socket/__init__.py", line 34, in <module>
    mhapi = gui3d.app.mhapi
AttributeError: 'MHApplication' object has no attribute 'mhapi'
```

Not sure how MH versions, but I'm running at this commit, 
```
origin  git@github.com:makehumancommunity/makehuman.git
b0ca7c88 (HEAD -> master, origin/master, origin/HEAD) Remove blendertools and docs from ppa build
```

**Comment by gabrielmontagne** [comment]
Ah!  I realized that I needed to also install this one, 
https://github.com/makehumancommunity/community-plugins-mhapi

It didn't register when I read the description here, 
http://www.makehumancommunity.org/content/plugins.html

Thanks. Sorry for the noise, and here for posterity if some other lost soul gets this error.
